### ISSUE TITLE
[1.15 Protocollib] Custom Tab Complete

### ISSUE THREAD

**Issue by NikV2** [PolskiStevek/EpicGuard#16] opened 2020-03-01 23:05 UTC
Hey, apparently the Custom Tab complete option does nothing at all.
Tried even the default config.

Using latest protocollib and Paper 1.15.2

**Comment by NikV2** [comment] 2020-03-01 23:14
And no perms are given, tried with both no perms at all and even de opped

**Comment by PolskiStevek** [comment] 2020-03-02 05:59
Blocking tab complete is also not working. On older versions working fine.

**Comment by PolskiStevek** [comment] 2020-03-02 15:18
The issue is caused by the new TabComplete system in the new Minecraft versions. Packets are only sent on arguments, and not actually on clicking TAB. This probably can't be fixed, as I don't know how to intercept new PacketPlayInTabComplet packet and make it backwards compatible. I'm not closing it, as maybe in future ill find a way to make it compatible with new versions.
Going to see PacketWrapper/ProtocolLib code, maybe ill find something useful.

**Comment by PolskiStevek** [comment] 2020-03-12 11:33
I have an idea of how to fix this: Clients sends PacketPlayInTabComplete, and the server sends PacketPlayOutTabComplete as a response. My idea is to modify the second out packet.

**Comment by PolskiStevek** [comment] 2020-03-12 11:47
Well, nope. This can't be fixed in any way.

**Closed by PolskiStevek** 2020-03-12 11:47 UTC
Labels: bug
